;                          M@@@@@@@r                          
;                       ;@@@h    ,@@@B                       
;                     3@@@r         M@@@:                       /$$      /$$                               /$$                     /$$
;                   9@@@,     ;r:     h@@@;                    | $$  /$ | $$                              |__/                    | $$
;                 #@@#      B@@@@@s     r@@@3                  | $$ /$$$| $$  /$$$$$$   /$$$$$$  /$$$$$$$  /$$ /$$$$$$$   /$$$$$$ | $$
;              ;@@@G     ,#@@@@@@@@@h     ,@@@S                | $$/$$ $$ $$ |____  $$ /$$__  $$| $$__  $$| $$| $$__  $$ /$$__  $$| $$
;            r@@@s     r@@@@@@Gh#@@@@@B      #@@#              | $$$$_  $$$$  /$$$$$$$| $$  \__/| $$  \ $$| $$| $$  \ $$| $$  \ $$|__/
;          2@@@;     3@@@@@@S     @@@@@@#,     G@@@;           | $$$/ \  $$$ /$$__  $$| $$      | $$  | $$| $$| $$  | $$| $$  | $$    
;        B@@@:     H@@@@@@@@;     @@@@@@@@@;     3@@@r         | $$/   \  $$|  $$$$$$$| $$      | $$  | $$| $$| $$  | $$|  $$$$$$$ /$$
;     :@@@B     :#@@@@@@@@@@s     @@@@@@@@@@@3     r@@@h       |__/     \__/ \_______/|__/      |__/  |__/|__/|__/  |__/ \____  $$|__/
;   ;@@@2     ;@@@@@@@@@@@@@s     @@@@@@@@@@@@@H     :@@@G                                                               /$$  \ $$   
; ;@@@r     s@@@@@@@@@@@@@@@s     @@@@@@@@@@@@@@@#:     B@@B                                                            |  $$$$$$/    
;@@@B     ;@@@@@@@@@@@@@@@@@s     @@@@@@@@@@@@@@@@@@      @@@                                                            \______/    
;#@@@      @@@@@@@@@@@@@@@@@r     @@@@@@@@@@@@@@@@@G      @@@   Do not modify this file. Please use the settings windows in NXT-OS to edit setttings.
;  B@@B     :B@@@@@@@@@@@@@@r     @@@@@@@@@@@@@@@3     r@@@r    Many settings in this file have to be changed through other interfaces, such as the 
;    B@@@:     H@@@@@@@@@@@@@3;,;#@@@@@@@@@@@@@;     h@@@r      ones built in to widgets. 
;      h@@@;     3@@@@@@@@@@@@@@@@@@@@@@@@@@#:     G@@@,     
;        r@@@3     ;@@@@@@@@h     @@@@@@@@G      @@@#           Modifying this file could lead to problems with NXT-OS.
;          ,@@@G     :#@@@@@G     @@@@@@h     ;@@@H          
;             #@@#      G@@@@@@@@@@@@@r     s@@@s            
;               9@@@;     h@@@@@@@@@;     H@@@;              
;                 s@@@r     r@@@@#      M@@@                 
;                   ;@@@S            :@@@G                   
;                     :@@@B        r@@@h                     
;                        B@@@,   3@@@r                       
;                          ;@@@@@@G                          



[Variables]
Animate.Hud=1
Animation.Dock=5
Animation.FPS=16
Animation.Hud=40
Animation.Notify=50

CenterClock.AlbumDisplay=1
CenterClock.Behavior=Hdd
CenterClock.DriveLetter=C
CenterClock.Glass=1
CenterClock.NoArtStyle=2
CenterClock.Scale=1
CenterClock.SmoothSeconds=1
CenterClock.TickStyle=0

Color.Clipboard=0
Color.ClockDot=255,255,255
Color.ClockMain=255,255,255
Color.ClockSecHand=255,255,255,180
Color.ClockSecondary=255,255,255,180
Color.Dock=20,126,255,150
Color.DockFolderBackground=255,255,255
Color.DockFolderText=80,80,80
Color.DockFolderTint=80,80,80
Color.DockIcon=255,211,66
Color.Glass=0,86,191,150
Color.Main=255,211,66
Color.Notification=1
Color.Scout=0
Color.TopLabel=1

Dock.CenterAction=[Shell:::{2559a1f8-21d7-11d4-bdaf-00c04f60b9f0}]
Dock.CenterActionStock=Scout
Dock.CenterIcon=Resources\Images\Center\Center.png
Dock.Scale=1
Dock.ShowCenterGlass=0
Dock.ShowGlass=0

GameDrawer.Bnet=0
GameDrawer.CloseOnGame=0
GameDrawer.DrawerMode=1
GameDrawer.GameTabPosition=1
GameDrawer.Offset=4
GameDrawer.SortMode=LastPlayed
GameDrawer.Steam=0
GameDrawer.SteamPath=C:\Program Files (x86)\Steam\
GameDrawer.SteamShortcuts=0
GameDrawer.SteamUserDataID=154275972

GameMode.Enable=0
GameMode.Mode=0
GameMode.Blacklist=Spotify|ui32|Notion|chrome||NVIDIA GeForce Experience|
GameMode.Known=StardewModdingAPI|
GameMode.Detect=35

LockScreen.Dots=0
LockScreen.Enable=1
LockScreen.SecondDots=0
LockScreen.ShowBG=0
LockScreen.Wallpaper=#@#\Wallpapers\Wallpaper.png
LockScreen.WallpaperB=1
LockScreen.Tint=154

Monitor.MainNum=1
Monitor.MainX=#SCREENAREAX@1#
Monitor.MainY=#SCREENAREAY@1#
Monitor.MainW=#SCREENAREAWIDTH@1#
Monitor.MainH=#SCREENAREAHEIGHT@1#

Notification.Battery=0
Notification.CapsLock=0
Notification.Duration=5
Notification.HudDuration=2
Notification.MicCheck=1
Notification.Music=0
Notification.NumLock=0
Notification.Speakers=0
Notification.Update=0

Overlay.Widget.HDD.1=C
Overlay.Widget.HDD.2=D
Overlay.Widget.HDD.3=E
Overlay.Widget.HDD.4=F
Overlay.Widget.Sticky.Text=81% at 12:15

Scout.IndexExtensions=lnk;
Scout.IndexInterval=2
Scout.IndexTargets=%SystemDrive%\ProgramData\Microsoft\Windows\Start Menu\Programs|%AppData%\Microsoft\Windows\Start Menu\Programs|
Scout.IndexTime=5
Scout.IndexTimeMod=12
Scout.IndexWin=0
Scout.LastIndex=1645037631
Scout.NextIndex=1645221600
Scout.ShowPath=0

System.AutoVis=Spotify
System.ClipboardKey=V
System.ClipboardKeyModifier2=ALT
System.ClipboardKeyModifier=CTRL
System.ClipboardKeyState=1
System.DateFormat=%A, %B %#d
System.DateLang=Local
System.DisplayPos=0
System.InputForce=0
System.InstallFinished=1
System.InstallType=Minimal
System.LockTimeout=0
System.OverlayLauncherKey=F10
System.OverlayLauncherKeyModifier=ALT
System.OverlayLauncherKeyState=0
System.OverlayWidgetsKey=TAB
System.OverlayWidgetsKeyModifier=CTRL
System.OverlayWidgetsKeyState=0
System.Player=Spotify
System.PlayerPlugin=Spotify
System.ScoutKey=F8
System.ScoutKeyModifier=ALT
System.ScoutKeyState=0
System.TimeFormat=1
System.UserName=JJame
System.VisualizerMode=1

Top.Quick.AutoHide=0
Top.Quick.Order=lock|power|add|overlaylauncher|
Top.Quick.ShowLabel=0
Top.Scale=1
Top.Widget.Clock.Align=LeftTop
Top.Widget.HDD.Drive1=C
Top.Widget.HDD.Drive2=D
Top.Widget.HDD.Drive3=F
Top.Widget.TextClock.Align=LeftTop
Top.Widget.TextClock.BoldSetting=#FirstWordBold#
Top.Widget.TextClock.Case=None
Top.Widget.TextClock.Date=0
Top.Widget.TextClock.Space=" "
Top.WidgetEditMode=0

Visualizer.Style=Bars
Visualizer.Smoothing=1
Visualizer.NumBars=51
Visualizer.FFTSize=128
Visualizer.FFTOverlap=64
Visualizer.FFTAttack=10
Visualizer.FFTDecay=125
Visualizer.FreqMin=20
Visualizer.FreqMax=160
Visualizer.Sensitivity=55
